version: '3.8'

services:
  porkbun-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: porkbun-mcp-server
    ports:
      - "${MCP_PORT:-8000}:${MCP_PORT:-8000}"
    environment:
      # Porkbun API Configuration
      - PORKBUN_API_KEY=${PORKBUN_API_KEY}
      - PORKBUN_SECRET_API_KEY=${PORKBUN_SECRET_API_KEY}
      - PORKBUN_BASE_URL=${PORKBUN_BASE_URL:-https://api.porkbun.com/api/json/v3}
      - TIMEOUT=${TIMEOUT:-30}
      # MCP Server Configuration
      - MCP_PORT=${MCP_PORT:-8000}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "python -c 'import httpx; httpx.get(\"http://localhost:${MCP_PORT:-8000}/health\")'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - porkbun-mcp-network

networks:
  porkbun-mcp-network:
    driver: bridge
